name: Go Dev Builds

on:
  push:
    branches: [ "develop" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set Up Build Env
      run: |
        mkdir -p ./dist

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build -o ./dist/mc-server-downloader_linux-amd64 ./cmd/mc-server-downloader

    - name: Build for Windows 64bit
      run: GOOS=windows GOARCH=amd64 go build -o ./dist/mc-server-downloader.exe ./cmd/mc-server-downloader

    - name: Build for Mac OS M1
      run: GOOS=darwin GOARCH=arm64 go build -o ./dist/mc-server-downloader_darwin-arm64 ./cmd/mc-server-downloader

    - name: Archive Dev Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "executable artifacts"
        path: dist

